### ISSUE TITLE
multivariate_preprocess increases the number of rows, occasionally beyond MaxRowsError threshold

### ISSUE THREAD

**Issue by schicks** [piccolbo/altair_recipes#10]
Converting a dataframe to long form as is done in [multivariate_preprocess](https://github.com/piccolbo/altair_recipes/blob/a5a19ec8c7dffefe8463436d5b9eb4096b4a67a7/altair_recipes/common.py#L211) will increase the number of rows for any multivariate wide form table. This leads to some surprising behavior. When I build a multivariate histogram myself following the example in altair;

```python
base = alt.Chart(frame.head(5000))
histograms = base.transform_fold(
    arms,
    as_=['Variant', 'Results']
).mark_area(
    opacity=0.3,
    interpolate='step'
).encode(
    alt.X('Results:Q', bin=alt.Bin(maxbins=100)),
    alt.Y('count()', stack=None),
    alt.Color('Variant:N')
)
histograms
```
This works fine because my frame is randomly distributed and the `head(5000)` guarantees that it fits nicely within the maxRowsError limit. However, when I try to do the same thing with the recipes version;

```python
ar.layered_histogram(frame.head(5000))
```
I get a maxRowsError. 

Cutting the number of rows further also isn't really viable, because with five series cutting the number of rows far enough starts to lose a lot of the shape of the distributions.

Would it be possible to instead do the transformation to long form with `transform_fold`, as in the altair docs? something like;

```python
def base_graph_multivariate(data, columns, group_by):
    assert (
        type(columns) == str or len(columns) == 1 or group_by is None
    ), "Wide or long format but not both"
    
    if group_by is None:  # convert wide to long
        data = data[columns]
        key = default(data.columns.name, "variable")
        value = "value"
        base = alt.Chart(data).transform_fold(columns, as_=[key, value])
    else:
        key = group_by
        value = columns if type(columns) is str else columns[0]
    return base, key, value
```

I'm new to the code base, if this is a bad idea I would love to get some context around what I'm not understanding.

**Comment by piccolbo** [comment]
I was hoping that the 5000 limit would be lifted soon. I will look into your idea. I wanted to separate any data processing from the graphics part and do the former in pandas. I don't think one library should try to do everything.

**Comment by schicks** [comment]
That makes sense, but it seems like altair is committed to the limit. What about using one of the [data_transformers](https://altair-viz.github.io/user_guide/faq.html#local-filesystem) provided by altair in the recipes to get around the limit?

**Comment by piccolbo** [comment]
Interesting. This sounds like more than a workaround, it sounds like a list of alternative ways to provide data that's not subject to the limit.  I need to look at the pros and cons of each method. Ease of sharing and ease of publishing. The idea is I can send you one file, you open it in the browser done. Or push to your blog or some such. But we can keep that convenience when rows < 5000 and, say, use json when the simpler method is not available. Now you have to share two files or post two files. If you have 10 figs, now you have 11 files. Yet that is in alternative to being stuck. By the way, I noticed that there is a way to disable the maxrow limit, in the same page you pointed me to. That would be just a workaround, not a solution `alt.data_transformers.disable_max_rows()`

**Comment by piccolbo** [comment]
The json transformer generates empty charts for me. The local returns this error

```
NoSuchEntryPoint: No
'data_server' entry point found in group
'altair.vegalite.v3.data_transformer'
```

**Comment by piccolbo** [comment]
For the json transformer, I think it is a manifestation of this: https://github.com/altair-viz/altair/issues/1600 and unfortunately it is not solvable. Also, for your specific situation, since data transformer operate at a package level, you can experiment with all of them, there is nothing we need to change in altair_recipes unless we want to make it automatic or realize some other integration. Just add for instance a `alt.data_transformers.enable('json')` or `alt.data_transformers.disable_max_rows()` and see if either works for you. Let me know how it pans out.

**Comment by piccolbo** [comment]
It's a much more trivial problem

WARN Loading failed `altair-data-a26b06a79020e9368567c9f52832670a.json` Error: "404File not found"

**Comment by piccolbo** [comment]
So it seems that the transformer will write to CWD no matter what. Since my code is writing the html file elsewhere, and the url of the data points to  same dir as document, error ensues. There is an example in the transformers doc on how to write a transformer with flexibility on the write  location.

**Comment by piccolbo** [comment]
Something along these lines:
```
def to_json_rel(data, data_dir):
    cwd = os.getcwd()
    rel = os.path.relpath(cwd, data_dir)
    os.makedirs(data_dir, exist_ok=True)
    return alt.pipe(data, alt.to_json(filename=rel + "/{prefix}-{hash}.{extension}"))


alt.data_transformers.register("to_json_rel", to_json_rel)
alt.data_transformers.enable(
    "to_json_rel", data_dir="/Users/antonio/Projects/own/altair_recipes/tests/"
)
```

Based on this I am going to close for now, but feel free to reopen if warranted.
